language: python
matrix:
  include:
    - env: TOX_ENV=lint
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.5
    - python: 2.7
    - env: TOX_ENV=test-pytest-xdist

install:
  - pip install tox
  - export TOX_ENV=${TOX_ENV:-`tox --listenvs | grep "py${TRAVIS_PYTHON_VERSION/./}" | tr '\n' ','`}

script: tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
